MACRO(OPENCOG_ADD_ATOM_TYPES)
    SET(oneValueArgs SCRIPT_FILE INHERITANCE_FILE SCM_FILE PYTHON_FILE)
    SET(multiValueArgs HEADER_FILE DEFINITIONS_FILE)
    CMAKE_PARSE_ARGUMENTS(OTYPES "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    LIST(GET OTYPES_HEADER_FILE 0 H_FILE)
    LIST(GET OTYPES_DEFINITIONS_FILE 0 D_FILE)

    SET(HEADER_INCLUDES ${OTYPES_HEADER_FILE})
    LIST(REMOVE_AT HEADER_INCLUDES 0)
    SET(DEFINITIONS_INCLUDES ${OTYPES_DEFINITIONS_FILE})
    LIST(REMOVE_AT DEFINITIONS_INCLUDES 0)
    MESSAGE("SCRIPT_FILE: ${OTYPES_SCRIPT_FILE}\n"
            "INHERITANCE_FILE: ${OTYPES_INHERITANCE_FILE}\n"
            "SCM_FILE: ${OTYPES_SCM_FILE}\n"
            "PYTHON_FILE: ${OTYPES_PYTHON_FILE}\n"
            "HEADER_FILE: ${H_FILE}\n"
            "DEFINITIONS_FILE: ${D_FILE}\n")
    ADD_CUSTOM_COMMAND (
        COMMAND "${CMAKE_COMMAND}" -DDEFINITIONS_INCLUDES=${DEFINITIONS_INCLUDES} -DHEADER_INCLUDES=${HEADER_INCLUDES} -DSCRIPT_FILE=\"${CMAKE_CURRENT_SOURCE_DIR}/${OTYPES_SCRIPT_FILE}\" -DHEADER_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${H_FILE}\" -DDEFINITIONS_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${D_FILE}\" -DINHERITANCE_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${OTYPES_INHERITANCE_FILE}\" -DSCM_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${OTYPES_SCM_FILE}\" -DPYTHON_FILE=\"${CMAKE_CURRENT_BINARY_DIR}/${OTYPES_PYTHON_FILE}\" -P "${COGUTIL_DATA_DIR}/cmake/OpenCogAtomTypes.cmake"
        OUTPUT  "${CMAKE_CURRENT_BINARY_DIR}/${H_FILE}"
                "${CMAKE_CURRENT_BINARY_DIR}/${D_FILE}"
                "${CMAKE_CURRENT_BINARY_DIR}/${OTYPES_INHERITANCE_FILE}"
                "${CMAKE_CURRENT_BINARY_DIR}/${OTYPES_SCM_FILE}"
                "${CMAKE_CURRENT_BINARY_DIR}/${OTYPES_PYTHON_FILE}"
        DEPENDS "${OTYPES_SCRIPT_FILE}" "${COGUTIL_DATA_DIR}/cmake/OpenCogAtomTypes.cmake"
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        COMMENT "Generating opencog types"
    )
ENDMACRO(OPENCOG_ADD_ATOM_TYPES)